---
- name: A simple playbook that installs a list of apps
  hosts: all
  gather_facts: false
  
  vars:
    state: present
  
  tasks:
  
  - name: Use the apt package manager
    copy:
      content: "A brand new file"
      dest: /tmp/newfile.txt
    become: yes
